// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4IiqAvk4OpwuHdcpUkXoBMf-7eXJ62Kg',
    appId: '1:792211323468:web:d49ffeedb5fc3d638ad2e9',
    messagingSenderId: '792211323468',
    projectId: 'lapor-book-508ac',
    authDomain: 'lapor-book-508ac.firebaseapp.com',
    storageBucket: 'lapor-book-508ac.appspot.com',
    measurementId: 'G-3DRLCK1G84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3B-ZiM_l6Qys2KvZUlkbsXyTbIN8LKLY',
    appId: '1:792211323468:android:8e2041df611ac3088ad2e9',
    messagingSenderId: '792211323468',
    projectId: 'lapor-book-508ac',
    storageBucket: 'lapor-book-508ac.appspot.com',
  );
}
